version: "3.8"

services:
  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
  django:
    platform: linux/amd64
    build:
      context: ./django-container
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./django-container/source:/source
    env_file: .env
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0:8000"
    depends_on:
      - db

volumes:
  postgres_data: